artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  URL: https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing
  locat_data_path: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

base_model:
  root_dir: artifacts/base_model
  vgg_model: artifacts/base_model/model.h5  


training:
  root_dir: artifacts/training
  vgg_model: artifacts/base_model/model.h5
  final_model:artifacts/training/

  